name: Terraform EC2 via OIDC (No Secrets in GitHub)

on:
  workflow_dispatch:
  push:
    branches: [ "main" ]

permissions:
  id-token: write   # required for OIDC
  contents: read

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Configure AWS credentials via OIDC (no secrets)
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::294944667890:role/OICD
          aws-region: us-east-1
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Terraform Init
        run: terraform init

      # - name: Terraform Validate
      #   run: terraform validate

      # - name: Terraform Plan
      #   run: terraform plan -input=false

      - name: Destroy with variables
        run: terraform destroy -auto-approve

      # - name: Terraform Apply (auto-approve for demo)
        # if: github.ref == 'refs/heads/main'
        # run: terraform apply -auto-approve -input=false
